### ISSUE TITLE
Styling missing for individual pages

### ISSUE THREAD

**Issue by kishaningithub** [rgardler/rgardler.github.io#2]
The style sheets are not getting loaded for any of the individual pages

https://rgardler.github.io/2016/02/10/create_keys_for_an_application_to_manage_azure
https://rgardler.github.io/2015/07/21/schedule-jekyll-posts

When i inspected the html i found `/twitter` is missing in urls

```bash
<link rel="stylesheet" href="/assets/themes//bootstrap/css/bootstrap.2.2.2.min.css">
<link href="/assets/themes//css/style.css?body=1" rel="stylesheet" type="text/css" media="all">
<link rel="stylesheet" type="text/css" media="all" href="/assets/themes//css/syntax.css">
```

This should actually be 

```bash
<link rel="stylesheet" href="/assets/themes/twitter/bootstrap/css/bootstrap.2.2.2.min.css">
<link href="/assets/themes/twitter/css/style.css?body=1" rel="stylesheet" type="text/css" media="all">
<link rel="stylesheet" type="text/css" media="all" href="/assets/themes/twitter/css/syntax.css">
```

### Current look without the style sheets

![screenshot 2018-11-27 at 5 03 23 pm](https://user-images.githubusercontent.com/763760/49094628-f709ca00-f266-11e8-8297-123e68fe0029.png)

**Comment by rgardler** [comment]
Thanks for this. I have now fixed it.

Maybe I'll write some more content too ;-)
